name: pokemonland
services:
  db:
    restart: always
    container_name: pokemon_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pokemon-vol:/var/lib/postgresql/data

    networks:
      - main
  api:
    depends_on:
      - db
    restart: always
    container_name: pokemon_api

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - ./src:/app/src
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
volumes:
  pokemon-vol:
